### PR TITLE
Fix Adolescentes page2: Actividad Fisica

### PR DESCRIPTION
**Pull request by laughedelic**
- missing message for `sentadoMinutos`
- last two fields are not filled from the DB
- hours-fields have wrong types and input format (should be `hh:mm` in the form, minutes (`Int`) in the DB)

### CODE REVIEW

**Comment by laughedelic** [comment]
Fixed everything except the hh:mm input format. It's not so simple:
- there is [`<input type="time">`](https://www.w3.org/TR/2012/WD-html-markup-20120315/input.time.html), but it's strange, works differently in different browsers and shows time in AM/PM format
- it could be `text` input with `pattern` attribute, but it's a bit [involved](http://stackoverflow.com/questions/14772142/24-hour-time-regex-for-html-5?noredirect=1&lq=1)

I'll open another issue for it.

**Comment by vdiaz-biomed** [comment]
As an idea, if you still haven't fixed this, maybe it would be helpful if you divided hours and minutes to be filled separately by the user (one field for hours and one for minutes). Then, when the form is processed, some programming could turn all into minutes, add the result and store it in the database.

**Comment by laughedelic** [comment]
Yes, this is another possible solution. But I'm leaving this to be solved later, because there are more important issues.

**Comment by epareja** [comment]
I agree, better to progress and then fix the issue of the time

**Pull request merged**
