### PR TITLE
Form-specific styles

### PR DESCRIPTION
**Pull request by laughedelic**
See DoPlanning [message](https://doplanning.net/?abb=web4bio7&area=2024&message=22518) from Vicente:

> - La hoja de estilos que usen otros formularios podría ser distinta. El código que carga esa hoja está en la línea 13 de app/views/templates/main.scala.html. En adolescentes se carga app/assets/stylesheets/form_children.css; en otros formularios se podría cargar otra diferente. 
> - La imagen de cabecera será distinta en cada página del formulario de alumnos. Echa un vistazo a cómo la incluyo (código de la línea 42 de app/views/templates/main.scala.html). El resto de imagenes las subo después, pero se llaman igual, excepto que varía el número (form_page_img_2.jpg, form_page_img_3.jpg, y así).

### CODE REVIEW

**Comment by laughedelic** [comment]
Both issues are addressed. @vdiaz-biomed take a look at the result. It also addresses this

> Donde pone CUESTIONARIO ALUMNO me gustaría que pusiera CUESTIONARIO DE y el nombre del alumno

And here goes the explanation of what is happening: 
First, each template has somewhere in the beginning a line that looks like `@(....)` with this template's parameters.

So what I've done here:
1. added `views/adolescentes/common.scala.html` template and changed all `views/adolescentes/page...` templates to use it
2. in `adolescentes/common` I added styles that are specific for all these pages (and removed them from `templates/main`)
3. modified all basic templates (logged, default, main) to add `headTitle` and `headImage` parameters (see [how they are used in `main` now](https://github.com/doplanning/si-eso/pull/79/files#diff-13a3acf31a9431fd84356553a53eee42R43)): 
    - In `adolescentes/common` I set `headTitle` which is common for all pages 
    - and on each page I set `headImage` which is specific for each page

**Comment by laughedelic** [comment]
Note that on the `index` page content is misplaced. I this I will add another template that is common for all questionnaires and has this `<div class="container">` with head and content.

**Comment by laughedelic** [comment]
I added `templates/form` with those `form-head-container` and `form-content-container`. So index now doesn't have it. But it doesn't fix the placement of content. So I guess it's related to the CSS used there (because index now doesn't use `form_children.css`).

**Comment by vdiaz-biomed** [comment]
I have merged you request to see the results.
It looks great except for the index pages. That can be fixed by loading a "default" css file in all pages to control the general layout positioning in all pages. I am going to make this default css and load it to the repository, and then you include it in all pages. 

On the other side, I would'nt mind if the signin page loaded the styles corresponding to the user, that is, if the signin page for children forms has the same styles as the children forms themselves. Can this be addressed?

Thanks for the work!

**Comment by laughedelic** [comment]
> I have merged you request to see the results.

OK. You can also see the results by "switching" to the branch and rerunning sbt:

```
> git checkout pr/79
> sbt test; run
```



> signin page loaded the styles corresponding to the user, that is, if the signin page for children forms has the same styles as the children forms themselves. Can this be addressed?

I'm not sure about the sign-in page, which seems to be common for everybody (and until user signed in, how do you know if it's alumno or somebody else?), but we have separate index pages for each type of users (see `app/views/indexAlumno.scala.html` for eaxample). So we can add specific styles there.

**Pull request merged**
